[supervisord]
nodaemon=true
logfile=/var/www/html/storage/logs/supervisord.log
logfile_maxbytes=0

[program:supervisord-log-forwarder]
command=tail -F -n 0 /var/www/html/storage/logs/supervisord.log
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:logrotate]
command=sh -c "while true; do sleep 3600; /usr/sbin/logrotate --state /var/www/html/storage/logs/logrotate.state /etc/logrotate.d/supervisord; done"
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frankenphp]
command=frankenphp run --config /etc/frankenphp/Caddyfile --adapter caddyfile
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=8
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:laravel-schedule]
command=php /var/www/html/artisan schedule:work
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
